ifndef TOPDIR
	TOPDIR = $(abspath ../../../)
endif
ifndef SRCDIR
	SRCDIR = $(abspath ../)
endif

NAME := parse_bonus.a
HEAD := parse_bonus.h
SRCS := parse_bonus.c \
		convertor_bonus.c \
		constructor_bonus.c \
		constructor2_bonus.c \
		parse_utils_bonus.c \
		split_bonus.c \
		split_utils_bonus.c \
		validate_bonus.c \

include $(TOPDIR)/include_make/Variable.mk
include $(TOPDIR)/include_make/Link.mk
include $(TOPDIR)/include_make/Recipe_subsrc.mk