ifndef TOPDIR
	TOPDIR = $(abspath ../../)
endif

NAME := libget_next_line.a
HEAD := get_next_line.h
SRCS := get_next_line.c \
		get_next_line_utils.c \

LDLIBS := -lft

include $(TOPDIR)/include_make/Variable.mk
include $(TOPDIR)/include_make/Link.mk
include $(TOPDIR)/include_make/Recipe_lib.mk