ifndef TOPDIR
	TOPDIR = $(abspath ../../../)
endif
ifndef SRCDIR
	SRCDIR = $(abspath ../)
endif

NAME := vector_bonus.a
HEAD := vector_bonus.h
SRCS := vec_bonus.c \
		vec_cal_bonus.c \
		vec_cal_s_bonus.c \

include $(TOPDIR)/include_make/Variable.mk
include $(TOPDIR)/include_make/Link.mk
include $(TOPDIR)/include_make/Recipe_subsrc.mk